name: chromosome_client
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  f_logs: ^2.0.1
  native_opencv:
    # When depending on this package from a real application you should use:
    #   native_opencv: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  get: 4.6.5
  fluent_ui: 3.12.0
  desktop_multi_window: 0.2.0
  pluto_grid: 5.0.6
  permission_handler: ^7.2.0
  menubar:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      ref: 17d4710c17f4913137e7ec931f6e71eaef443363
      path: plugins/menubar
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      ref: 17d4710c17f4913137e7ec931f6e71eaef443363
      path: plugins/window_size
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/analyse/
    - assets/images/Cell/
    - assets/images/Cell/Cell1/
    - assets/images/Cell/Cell2/
    - assets/images/Cell/Cell3/
    - assets/images/Cell/Cell4/
    - assets/images/Cell/Cell5/
    - assets/images/index/
    - assets/images/Loading/
    - assets/images/login/
    - assets/images/logo/
    - assets/images/showfour/
    - assets/images/showthree/
    - assets/images/superview/
    - assets/images/test/
    - assets/images/tools/
  uses-material-design: true

